[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "afri-auth-sms"
version = "0.1.1"
description = "Plug and play OTP authentication for African telecom providers"
readme = "README.MD"
requires-python = ">=3.10"
license = {text = "MIT"}

authors = [
    {name = "AdamKatani"}
]

dependencies = [
    "fastapi",
    "uvicorn",
    "redis",
    "africastalking",
    "python-dotenv",
    "typer"
]

[project.urls]
Homepage = "https://github.com/AdamMashaka/africastalking-kit-sms"
Repository = "https://github.com/AdamMashaka/africastalking-kit-sms"

[project.scripts]
afri-auth-sms = "afri_auth.cli:app"

[tool.setuptools.packages.find]
include = ["afri_auth*"]